# Baseline configuration for RFCN training on 5% of VOC07

_BASE_: "baseline_L=07_R50RFCN.yaml"
DATASETS:
  MODE: "RANDOM_SPLIT"
  SUP_PERCENT: 5  # Use only 5% of images for supervision
  RANDOM_SPLIT_SEED: 42
SOLVER:
  CHECKPOINT_PERIOD: 500  # Dump the model weights more often
TEST:
  EVAL_PERIOD: 500  # Evaluate more often