# CSD configuration for RFCN training on 5% VOC07 + 95% VOC07 as unlabeled data
# See `config/config.py` for details on parameters

_BASE_: "csd_L=07_U=12_R50RFCN.yaml"
DATASETS:
  MODE: "RANDOM_SPLIT"  # Split training dataset into labeled and unlabeled subsets
  SUP_PERCENT: 5  # Use only 5% of images for supervision; rest as unlabeled
  RANDOM_SPLIT_SEED: 42
SOLVER:
  CHECKPOINT_PERIOD: 500  # Dump the model weights more often
  CSD_WEIGHT_SCHEDULE_RAMP_T0: 1
  CSD_WEIGHT_SCHEDULE_RAMP_T1: 5000  # Make the CSD weight ramp-up a bit faster
  CSD_WEIGHT_SCHEDULE_RAMP_T2: 7000
  CSD_WEIGHT_SCHEDULE_RAMP_T: 12000
TEST:
  EVAL_PERIOD: 500  # Evaluate more often