# CSD configuration for RFCN training on VOC07 + VOC12 as unlabeled data
# See `config/config.py` for details on parameters

_BASE_: "baseline_VOC07_R50_RFCN.yaml"
MODEL:
  META_ARCHITECTURE: "CSDGeneralizedRCNN"
  ROI_HEADS:
    NAME: "CSDStandardROIHeads"
SOLVER:
  IMS_PER_BATCH: 32
  IMS_PER_BATCH_LABELED: 16
  IMS_PER_BATCH_UNLABELED: 16
  CSD_WEIGHT_SCHEDULE_RAMP_BETA: 0.5
  CSD_WEIGHT_SCHEDULE_RAMP_T0: 2000
  CSD_WEIGHT_SCHEDULE_RAMP_T1: 2001
  CSD_WEIGHT_SCHEDULE_RAMP_T2: 2002
  CSD_WEIGHT_SCHEDULE_RAMP_T: 2003
DATASETS:
  TRAIN_UNLABELED: ("voc_2012_trainval",)
WANDB_LOG_FREQ: 30
VIS_PERIOD: 300
VIS_IMS_PER_GROUP: 3
VIS_MAX_PREDS_PER_IM: 40
VIS_TEST: True