# See `config/config.py` for details on parameters

_BASE_: "faster_rcnn_R_50_FPN.yaml"
VERSION: 2
MODEL:
  META_ARCHITECTURE: "CSDGeneralizedRCNN"
  ROI_HEADS:
    NAME: "CSDStandardROIHeads"
SOLVER:
  IMS_PER_BATCH: 8
  IMS_PER_BATCH_LABELED: 4
  IMS_PER_BATCH_UNLABELED: 4
  CSD_WEIGHT_SCHEDULE_RAMP_BETA: 1.0
  CSD_WEIGHT_SCHEDULE_RAMP_T0: 1
  CSD_WEIGHT_SCHEDULE_RAMP_T1: 20000
  CSD_WEIGHT_SCHEDULE_RAMP_T2: 10000
  CSD_WEIGHT_SCHEDULE_RAMP_T: 70000
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TRAIN_UNLABELED: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
USE_WANDB: True
WANDB_PROJECT_NAME: "csd-detectron2"
VIS_PERIOD: 200
VIS_IMS_PER_GROUP: 3
VIS_MAX_PREDS_PER_IM: 40
VIS_TEST: True
TEST:
  EVAL_PERIOD: 1000