# See `config/config.py` for details on parameters

_BASE_: "baseline_VOC07_R50_RFCN.yaml"
MODEL:
  META_ARCHITECTURE: "CSDGeneralizedRCNN"
  ROI_HEADS:
    NAME: "CSDStandardROIHeads"
SOLVER:
  IMS_PER_BATCH: 8
  IMS_PER_BATCH_LABELED: 4
  IMS_PER_BATCH_UNLABELED: 4
  CSD_WEIGHT_SCHEDULE_RAMP_BETA: 0.5
  CSD_WEIGHT_SCHEDULE_RAMP_T0: 1
  CSD_WEIGHT_SCHEDULE_RAMP_T1: 6000
  CSD_WEIGHT_SCHEDULE_RAMP_T2: 1000
  CSD_WEIGHT_SCHEDULE_RAMP_T: 18000
DATASETS:
  TRAIN_UNLABELED: ("voc_2012_trainval",)
USE_WANDB: True
WANDB_LOG_FREQ: 30
WANDB_PROJECT_NAME: "csd-detectron2"
VIS_PERIOD: 300
VIS_IMS_PER_GROUP: 3
VIS_MAX_PREDS_PER_IM: 40
VIS_TEST: True