# See `config/config.py` for details on parameters

_BASE_: "faster_rcnn_R_50_FPN.yaml"
VERSION: 2
MODEL:
  META_ARCHITECTURE: "CSDGeneralizedRCNN"
  ROI_HEADS:
    NAME: "CSDStandardROIHeads"
SOLVER:
  BASE_LR: 0.002
  IMS_PER_BATCH: 2
  IMS_PER_BATCH_LABELED: 1
  IMS_PER_BATCH_UNLABELED: 1
  CSD_WEIGHT_SCHEDULE_RAMP_BETA: 1
  CSD_WEIGHT_SCHEDULE_RAMP_T0: 100
  CSD_WEIGHT_SCHEDULE_RAMP_T1: 20000
  CSD_WEIGHT_SCHEDULE_RAMP_T2: 10000
  CSD_WEIGHT_SCHEDULE_RAMP_T: 70000
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TRAIN_UNLABELED: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
DATALOADER:
  NUM_WORKERS: 1