# See `config/config.py` for details on parameters

_BASE_: "faster_rcnn_R_50_FPN.yaml"  # TODO: 101 in paper
VERSION: 2
MODEL:
  META_ARCHITECTURE: "CSDGeneralizedRCNN"
  ROI_HEADS:
    NAME: "CSDStandardROIHeads"
    BATCH_SIZE_PER_IMAGE: 80
    POSITIVE_FRACTION: 0.25  # In CSD-RFCN MAX_NUM_GT_BOXES is 20
  ANCHOR_GENERATOR:
    SIZES: [[8, 16, 32]]
SOLVER:
  IMS_PER_BATCH: 8
  IMS_PER_BATCH_LABELED: 7
  IMS_PER_BATCH_UNLABELED: 1
  CSD_WEIGHT_SCHEDULE_RAMP_BETA: 1
  CSD_WEIGHT_SCHEDULE_RAMP_T0: 100
  CSD_WEIGHT_SCHEDULE_RAMP_T1: 20000
  CSD_WEIGHT_SCHEDULE_RAMP_T2: 10000
  CSD_WEIGHT_SCHEDULE_RAMP_T: 70000
  BASE_LR: 0.001
  STEPS: (30000,)
  MAX_ITER: 60000
  WARMUP_ITERS: 100
INPUT:
  MIN_SIZE_TRAIN: (400, 500, 600, 700, 800)
  MAX_SIZE_TRAIN: 1000
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TRAIN_UNLABELED: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
DATALOADER:
  NUM_WORKERS: 1  # TODO: change.
